<root>
  <app layoutGap="1" useExtension="false" cutImage="true" layoutMath="2" autoLayout="true" freeSize="false" canvasSize="1024,1024"/>
  <items>
    <item label="ZZ" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\ZZ.png"/>
    <item label="arrow1" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\arrow1.png"/>
    <item label="arrow2" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\arrow2.png"/>
    <item label="arrow3" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\arrow3.png"/>
    <item label="blue" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\blue.png"/>
    <item label="btn1_beijing" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\btn1_beijing.png"/>
    <item label="btn1_chengdu" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\btn1_chengdu.png"/>
    <item label="btn1_haerbing" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\btn1_haerbing.png"/>
    <item label="btn1_hongkong" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\btn1_hongkong.png"/>
    <item label="btn1_nanjing" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\btn1_nanjing.png"/>
    <item label="btn1_qingdao" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\btn1_qingdao.png"/>
    <item label="btn1_shanghai" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\btn1_shanghai.png"/>
    <item label="btn1_taibei" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\btn1_taibei.png"/>
    <item label="btn1_tianjin" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\btn1_tianjin.png"/>
    <item label="btn1_xian" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\btn1_xian.png"/>
    <item label="btn2_beijing" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\btn2_beijing.png"/>
    <item label="btn2_chengdu" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\btn2_chengdu.png"/>
    <item label="btn2_haerbing" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\btn2_haerbing.png"/>
    <item label="btn2_hongkong" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\btn2_hongkong.png"/>
    <item label="btn2_nanjing" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\btn2_nanjing.png"/>
    <item label="btn2_qingdao" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\btn2_qingdao.png"/>
    <item label="btn2_shanghai" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\btn2_shanghai.png"/>
    <item label="btn2_taibei" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\btn2_taibei.png"/>
    <item label="btn2_tianjin" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\btn2_tianjin.png"/>
    <item label="btn2_xian" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\btn2_xian.png"/>
    <item label="cat" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\cat.png"/>
    <item label="clear" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\clear.png"/>
    <item label="cloud_01" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\cloud_01.png"/>
    <item label="cloud_02" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\cloud_02.png"/>
    <item label="cloud_03" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\cloud_03.png"/>
    <item label="cloud_04" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\cloud_04.png"/>
    <item label="cloud_05" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\cloud_05.png"/>
    <item label="cloud_06" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\cloud_06.png"/>
    <item label="dot1" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\dot1.png"/>
    <item label="dot2" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\dot2.png"/>
    <item label="flag" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\flag.png"/>
    <item label="guangzhou" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\guangzhou.PNG"/>
    <item label="guangzhou2" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\guangzhou2.PNG"/>
    <item label="GZ" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\GZ.png"/>
    <item label="hole_00" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\hole_00.png"/>
    <item label="icon_suo" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\icon_suo.png"/>
    <item label="new" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\new.png"/>
    <item label="play" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\play.png"/>
    <item label="yellow" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\yellow.png"/>
    <item label="zhenzhou" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\zhenzhou.PNG"/>
    <item label="zhenzhou2" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\png_map\zhenzhou2.PNG"/>
    <item label="_0003_btn_on_02" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\_0003_btn_on_02.png"/>
    <item label="_0005_btn_off_04" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\_0005_btn_off_04.png"/>
    <item label="_0006_btn_off_03" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\_0006_btn_off_03.png"/>
    <item label="_0007_btn_off_02" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\_0007_btn_off_02.png"/>
    <item label="icon_city_" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\icon_city_.png"/>
    <item label="icon_new" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\icon_new.png"/>
    <item label="_0001_btn_on_03" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\_0001_btn_on_03.png"/>
    <item label="_0002_btn_on_04" file="C:\Users\hu_jingyuan\Desktop\svn_MengFangYan_H5\美术资源\大地图\_0002_btn_on_04.png"/>
  </items>
</root>